- name: hosting webpage on apache server
  hosts: all
  become: yes
  tasks: 
    - name: installing required services
      package:
        name:
          - apache2
          - wget
          - unzip
        state: present

    - name: downloading template
      shell: wget https://www.free-css.com/assets/files/free-css-templates/download/page287/cycle.zip

    - name: extracting template
      unarchive: 
        src: /home/ubuntu/cycle.zip
        dest: /var/www/html
        remote_src: yes