- name: hosting webpage on apache server
  hosts: all
  become: yes
  tasks: 
    - name: downloading services in loop 
      package:
        name: "{{item}}"
        state: present
      loop:
        - apache2
        - wget
        - unzip

    - name: downloading template
      get_url:
        url: https://www.free-css.com/assets/files/free-css-templates/download/page287/cycle.zip
        dest: /home/ubuntu
      
    
    - name: extracting template in same directory
      unarchive: 
        src: /home/ubuntu/cycle.zip
        dest: /home/ubuntu
        remote_src: yes
    
    - name: Removing existing index.html file from root directory of apache
      file:
        path: /var/www/html/index.html
        state: absent
    
    - name: moving extracted template files to root directory of apache 
      shell: cp -r /home/ubuntu/html/* /var/www/html