- name: variable value
  hosts: all
  vars:
    url: www.globalvariable.com
  var_files: 
    - filevar.yaml
  tasks:
    - name: task2
      debug: 
        msg: "the value of variable {{url}}"
      