- name: Gatheringfacts
  hosts: all
  tasks:
    - name: gathering facts about nodes
      debug:
        msg: 
          - "ip of node is {{ansible_hostname}}"
          - "distro of node is {{ansible_distribution}}"