- name: ignoring errors
  hosts: all
  tasks: 
    - name: ignore errors
      shell: ps -aux | grep java | grep -v grep
      ignore_errors: yes
    
    - name: print message
      debug: 
        msg: "server is running good enough"