- name: loop playbook
  hosts: all
  become: yes
  tasks:
    - name: printing variable in loop 
      package:
        name: "{{item}}"
        state: present
      loop:
        - httpd
        - nginx
        - mariadb-server
        - tree
        