- name: loop playbook
  hosts: all
  become: yes
  tasks:
    - name: downloading services in loop 
      package:
        name: "{{item}}"
        state: present
      loop:
        - apache2
        - nginx
        - mariadb-server
        - tree