- name: loop playbook
  hosts: all
  tasks:
    - name: printing variable in loop 
      debug: 
        msg: "{{item}}"
      loop:
        - http
        - nginx
        - mariadb-server
        - tree
        