- name: registering variable
  hosts: all
  tasks:
    - name:
      shell: uptime
      register: OUTPUT
      
    - name: printing registered variable
      debug: 
        msg: "{{OUTPUT.stdout}}"
      
    - name: registering variable
      shell: pwd
      register: pwd

    - name: printing registered variable
      debug: 
        msg: "{{pwd}}"