- name: file module demo
  hosts: all
  vars:
    mypath: "/home/ubuntu/deleteme"
  become: false
  tasks:
    - name: "{{ mypath }}" 
      ansible.builtin.file:
        path: "{{ mypath }}"
        state: present