- name: hosting webpage on apache server
  hosts: all
  become: yes
  tasks: 
    - name: installing required services
      package:
        name:
          - apache2
          - wget
          - unzip
        state: present